#!/usr/bin/env python3
"""One-command reproduction of every numerical artifact in the current paper.

The command is designed to run from the minimal local reproduction package.
It audits/rebuilds the Full-15 summary from raw predictions, recomputes the
development experiments, regenerates Tables 1--3 and Figures 2--4, and then
clean-compiles the paper.  The method figure is a design source and is copied,
not regenerated by this numerical pipeline.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
EVIDENCE = ROOT / "evidence"
PAPER_SOURCE = ROOT / "paper/source"
DEFAULT_OUTPUT = ROOT / "outputs/current"


class PipelineError(RuntimeError):
    pass


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(4 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def run(command: list[str], *, cwd: Path = ROOT) -> None:
    print("+", " ".join(command), flush=True)
    completed = subprocess.run(command, cwd=cwd, check=False)
    if completed.returncode:
        raise PipelineError(f"command failed with exit code {completed.returncode}: {command}")


def require_file(path: Path) -> Path:
    if not path.is_file():
        raise PipelineError(f"required file is missing: {path}")
    return path


def rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as source:
        return list(csv.DictReader(source))


def compare_csv(actual: Path, reference: Path) -> None:
    if rows(actual) != rows(reference):
        raise PipelineError(f"regenerated CSV differs from frozen paper evidence: {actual.name}")


def copy_generated(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def clean_output(output: Path) -> None:
    marker = output / ".sparc_reproduction_output"
    if output.exists():
        if not marker.is_file():
            raise PipelineError(f"refusing to replace unmarked output directory: {output}")
        shutil.rmtree(output)
    output.mkdir(parents=True)
    marker.write_text("generated by reproduce_sparc_current_paper.py\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--skip-paper", action="store_true",
                        help="Regenerate numerical artifacts without compiling LaTeX.")
    args = parser.parse_args()
    output = args.output_dir.resolve()
    python = args.python
    clean_output(output)

    runs = require_file(EVIDENCE / "main/reference_summary.json").parent / "runs"
    reference_summary = require_file(EVIDENCE / "main/reference_summary.json")
    reference_table1 = require_file(EVIDENCE / "main/reference_table1.csv")
    dataset = require_file(EVIDENCE / "development/utility_targets_dev15.npz")
    router_report = require_file(EVIDENCE / "development/router_report.json")
    reference_suite = EVIDENCE / "development/reference_suite"

    rebuilt_summary = output / "main/summary.json"
    run([
        python, str(SCRIPTS / "rebuild_sparc_paper_summary.py"),
        "--runs", str(runs), "--reference-summary", str(reference_summary),
        "--output", str(rebuilt_summary),
    ])
    table1_dir = output / "table1"
    run([
        python, str(SCRIPTS / "generate_sparc_full15_table1.py"),
        "--summary", str(rebuilt_summary), "--output-dir", str(table1_dir),
    ])
    compare_csv(table1_dir / "table1_full15.csv", reference_table1)

    suite = output / "development_suite"
    run([
        python, str(SCRIPTS / "run_sparc_development_experiment_suite.py"),
        "--dataset", str(dataset), "--router-report", str(router_report),
        "--output-dir", str(suite),
    ])
    run([
        python, str(SCRIPTS / "audit_sparc_development_suite.py"),
        "--suite", str(suite), "--dataset", str(dataset),
        "--router-report", str(router_report),
    ])
    for filename in (
        "table2_router_controls.csv", "table3_expert_bank_ablation.csv",
        "table3_gate_ablation.csv", "data_efficiency.csv",
    ):
        compare_csv(suite / filename, require_file(reference_suite / filename))

    artifacts = output / "paper_artifacts"
    run([
        python, str(SCRIPTS / "generate_sparc_followup_artifacts.py"),
        "--suite", str(suite), "--summary", str(rebuilt_summary),
        "--output-dir", str(artifacts),
    ])
    if (artifacts / "table4_cost").exists():
        raise PipelineError("current-paper pipeline unexpectedly generated removed Table 4")

    paper_pdf: Path | None = None
    if not args.skip_paper:
        if not PAPER_SOURCE.is_dir():
            raise PipelineError(f"paper source is missing: {PAPER_SOURCE}")
        paper_build = output / "paper"
        shutil.copytree(PAPER_SOURCE, paper_build)
        # Table 1's numerical CSV is regenerated and matched above.  The paper
        # keeps its hand-authored venue column and approved typography.
        copy_generated(require_file(artifacts / "table2_router_controls/table2_router_controls_fragment.tex"),
                       paper_build / "generated_tables/table2_router_controls.tex")
        copy_generated(require_file(artifacts / "table3_ablations/table3_ablations_fragment.tex"),
                       paper_build / "generated_tables/table3_ablations.tex")
        for stem, directory in (
            ("figure2_backend_gains", "figure2_backend_gains"),
            ("figure3_data_efficiency", "figure3_data_efficiency"),
            ("figure4_routing", "figure4_routing"),
        ):
            copy_generated(require_file(artifacts / directory / f"{stem}.pdf"),
                           paper_build / "figures" / f"{stem}.pdf")
        tectonic = shutil.which("tectonic") or str(Path.home() / ".local/bin/tectonic")
        run([tectonic, "main_fresh.tex", "--keep-logs"], cwd=paper_build)
        paper_pdf = require_file(paper_build / "main_fresh.pdf")

    report: dict[str, Any] = {
        "schema_version": 1,
        "status": "passed_current_paper_reproduction",
        "scope": "current paper only",
        "seed": 1109,
        "main_result_conditions": 75,
        "raw_prediction_records_checked": 300000,
        "development_rows_recomputed": 15000,
        "development_csvs_exactly_matched": 4,
        "tables_regenerated": [1, 2, 3],
        "result_figures_regenerated": [2, 3, 4],
        "removed_table4_generated": False,
        "rebuilt_summary_sha256": sha256(rebuilt_summary),
        "paper_pdf": str(paper_pdf) if paper_pdf else None,
        "paper_pdf_sha256": sha256(paper_pdf) if paper_pdf else None,
    }
    report_path = output / "REPRODUCTION_REPORT.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    try:
        main()
    except (OSError, PipelineError) as error:
        print(json.dumps({"status": "failed_current_paper_reproduction", "error": str(error)}, indent=2))
        raise SystemExit(2)
